"""Initial migration

Revision ID: 609ccac433d4
Revises:
Create Date: 2026-06-28 21:09:53.281411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609ccac433d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('school', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_outcome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=200), nullable=True),
    sa.Column('examples', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempt_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('learning_outcome_id', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('p_before', sa.Float(), nullable=False),
    sa.Column('p_after', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learning_outcome_id'], ['learning_outcome.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempt_log', schema=None) as batch_op:
        batch_op.create_index('ix_attempt_log_user_lo', ['user_id', 'learning_outcome_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('learning_outcome_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('teacher_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['learning_outcome_id'], ['learning_outcome.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_user', ['user_id'], unique=False)

    op.create_table('learning_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learning_outcome_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('min_mastery', sa.Float(), nullable=True),
    sa.Column('max_mastery', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['learning_outcome_id'], ['learning_outcome.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mastery_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('learning_outcome_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_level', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learning_outcome_id'], ['learning_outcome.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'learning_outcome_id', name='uq_mastery_user_lo')
    )
    with op.batch_alter_table('mastery_record', schema=None) as batch_op:
        batch_op.create_index('ix_mastery_user_lo', ['user_id', 'learning_outcome_id'], unique=False)

    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learning_outcome_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['learning_outcome_id'], ['learning_outcome.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('learning_outcome_id', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learning_outcome_id'], ['learning_outcome.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_log', schema=None) as batch_op:
        batch_op.create_index('ix_rec_log_user_time', ['user_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_log', schema=None) as batch_op:
        batch_op.drop_index('ix_rec_log_user_time')

    op.drop_table('recommendation_log')
    op.drop_table('question')
    with op.batch_alter_table('mastery_record', schema=None) as batch_op:
        batch_op.drop_index('ix_mastery_user_lo')

    op.drop_table('mastery_record')
    op.drop_table('learning_resource')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_user')

    op.drop_table('evidence')
    with op.batch_alter_table('attempt_log', schema=None) as batch_op:
        batch_op.drop_index('ix_attempt_log_user_lo')

    op.drop_table('attempt_log')
    op.drop_table('learning_outcome')
    op.drop_table('topic')
    op.drop_table('user')
    op.drop_table('subject')
    # ### end Alembic commands ###
